name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: Karthik-Nayak98/Greeting-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue_message: "Hello @${{github.actor}}, <br>
            Thank you for opening an issue. :partying_face: <br>"
          PR_message: "<h1> :partying_face: Congratulations :tada: </h1> <h3> :pray: Thank you @${{github.actor}} for taking out your time and contributing to our project. We will soon review this and if everything looks good it will be merged. Happy Contributing!</h3>"
